[package]
name = "execute-command"
version = "0.0.0"
edition = "2021"
description = "A simple library to execute commands"
license = "MIT OR Apache-2.0"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]
